# Generated by Django 2.0.1 on 2018-02-08 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('service_value', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('exp_date', models.DateField()),
                ('choosen_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approuved_offers', to=settings.AUTH_USER_MODEL)),
                ('interested_profiles', models.ManyToManyField(blank=True, related_name='applied_offers', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(blank=True, to='profiles.Skill')),
            ],
        ),
    ]
