# Generated by Django 2.0.1 on 2018-01-29 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gsm',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please insert a valid number', regex='^[0-9]{10}$')], verbose_name='Phone number'),
        ),
    ]
